Person.id=123
Person.name=madhu
Person.age=12
Person.langs=Telugu,Hindi,English

Address.addrId=11
Address.city=hyderabad
Address.state=telangana

Employee.eid=4
Employee.ename="nandu"

Department.did=9
Department.dname="testing"

Student.sid=2170
Student.sname="sowmya"

Course.cid=33
Course.cname="springboot"