/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-20 11:25:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.Admin;
import com.model.Question;
import java.util.List;

public final class createQuiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.Question");
    _jspx_imports_classes.add("com.model.Admin");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

Admin admin = (Admin) session.getAttribute("admin");
if (admin == null) {
	response.sendRedirect(request.getContextPath() + "/admin/login");
	return;
}
List<Question> questions = (List<Question>) request.getAttribute("questions");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\" />\r\n");
      out.write("<title>Create Quiz - Quiz App</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* Reset & base */\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background: #f5f7fa;\r\n");
      out.write("	color: #34495e;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".layout {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("}\r\n");
      out.write("/* Sidebar */\r\n");
      out.write(".sidebar {\r\n");
      out.write("	width: 260px;\r\n");
      out.write("	background: linear-gradient(180deg, #4e73df 0%, #224abe 100%);\r\n");
      out.write("	color: white;\r\n");
      out.write("	padding: 24px 20px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("	font-size: 22px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	margin-bottom: 36px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item {\r\n");
      out.write("	padding: 14px 18px;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	transition: background 0.25s ease;\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item:hover {\r\n");
      out.write("	background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu-item.active {\r\n");
      out.write("	background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("	box-shadow: inset 3px 0 0 #f1f1f1;\r\n");
      out.write("}\r\n");
      out.write("/* Main content */\r\n");
      out.write(".main-content {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	padding: 40px 50px;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	box-shadow: inset 0 0 20px #f0f0f0;\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("/* Form container */\r\n");
      out.write(".form-container {\r\n");
      out.write("	max-width: 900px;\r\n");
      out.write("	background: #f9fafc;\r\n");
      out.write("	padding: 32px 36px;\r\n");
      out.write("	border-radius: 14px;\r\n");
      out.write("	box-shadow: 0 4px 15px rgba(46, 61, 73, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	font-size: 28px;\r\n");
      out.write("	color: #2c3e50;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("/* Alerts */\r\n");
      out.write(".success, .error {\r\n");
      out.write("	padding: 14px 18px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	margin-bottom: 24px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".success {\r\n");
      out.write("	background: #d4edda;\r\n");
      out.write("	color: #155724;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error {\r\n");
      out.write("	background: #f8d7da;\r\n");
      out.write("	color: #721c24;\r\n");
      out.write("}\r\n");
      out.write("/* Form groups */\r\n");
      out.write(".form-group {\r\n");
      out.write("	margin-bottom: 28px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("	color: #5a636d;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"], select {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 14px 18px;\r\n");
      out.write("	border: 1.5px solid #ddd;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	transition: border-color 0.25s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"text\"]:focus, select:focus {\r\n");
      out.write("	border-color: #4e73df;\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("/* Question list */\r\n");
      out.write(".question-list {\r\n");
      out.write("	max-height: 400px;\r\n");
      out.write("	overflow-y: auto;\r\n");
      out.write("	border: 1.5px solid #ddd;\r\n");
      out.write("	padding: 20px 18px;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	background: white;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question-item {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: flex-start;\r\n");
      out.write("	gap: 12px;\r\n");
      out.write("	padding: 12px 10px;\r\n");
      out.write("	margin-bottom: 14px;\r\n");
      out.write("	border-radius: 8px;\r\n");
      out.write("	border: 1px solid #e0e6f0;\r\n");
      out.write("	transition: background-color 0.2s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question-item:hover {\r\n");
      out.write("	background-color: #f0f4ff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question-item input[type=\"checkbox\"] {\r\n");
      out.write("	margin-top: 6px;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	width: 18px;\r\n");
      out.write("	height: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question-item label {\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	color: #34495e;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	user-select: text;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".question-item small {\r\n");
      out.write("	color: #95a5a6;\r\n");
      out.write("	margin-left: 8px;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	font-size: 13px;\r\n");
      out.write("}\r\n");
      out.write("/* Button */\r\n");
      out.write(".btn {\r\n");
      out.write("	padding: 14px 36px;\r\n");
      out.write("	background: linear-gradient(135deg, #4e73df 0%, #224abe 100%);\r\n");
      out.write("	color: white;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	transition: background 0.3s ease, transform 0.15s ease;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn:hover {\r\n");
      out.write("	background: linear-gradient(135deg, #667eea 0%, #3b55d6 100%);\r\n");
      out.write("	transform: translateY(-2px);\r\n");
      out.write("}\r\n");
      out.write("/* No questions fallback */\r\n");
      out.write(".no-questions {\r\n");
      out.write("	padding: 16px;\r\n");
      out.write("	color: #999;\r\n");
      out.write("	font-style: italic;\r\n");
      out.write("	user-select: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"layout\">\r\n");
      out.write("		<aside class=\"sidebar\">\r\n");
      out.write("			<div class=\"logo\">🎯 QUIZ APP</div>\r\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\"\r\n");
      out.write("				class=\"menu-item\">📊 Dashboard</a> <a\r\n");
      out.write("				href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/quizManager\"\r\n");
      out.write("				class=\"menu-item\">📝 Quiz Manager</a> <a\r\n");
      out.write("				href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/questionList\"\r\n");
      out.write("				class=\"menu-item\">❓ Question Manager</a> <a\r\n");
      out.write("				href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/addQuestion\"\r\n");
      out.write("				class=\"menu-item\">➕ Add New Question</a> <a\r\n");
      out.write("				href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/createQuiz\"\r\n");
      out.write("				class=\"menu-item active\">🆕 Create Quiz</a>\r\n");
      out.write("		</aside>\r\n");
      out.write("\r\n");
      out.write("		<main class=\"main-content\">\r\n");
      out.write("			<div class=\"form-container\">\r\n");
      out.write("				<h2>Create Quiz</h2>\r\n");
      out.write("				<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/createQuiz\"\r\n");
      out.write("					method=\"post\">\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"quizTitle\">Quiz Title</label> <input type=\"text\"\r\n");
      out.write("							id=\"quizTitle\" name=\"quizTitle\" required>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label for=\"category\">Category</label> <select id=\"category\"\r\n");
      out.write("							name=\"category\" required>\r\n");
      out.write("							<option value=\"\">Select category</option>\r\n");
      out.write("							<option value=\"General\">General</option>\r\n");
      out.write("							<option value=\"Science\">Science</option>\r\n");
      out.write("							<option value=\"History\">History</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"form-group\">\r\n");
      out.write("						<label>Select Questions</label>\r\n");
      out.write("						<div class=\"question-list\">\r\n");
      out.write("							");

							if (questions != null && !questions.isEmpty()) {
								for (Question q : questions) {
							
      out.write("\r\n");
      out.write("							<div class=\"question-item\">\r\n");
      out.write("								<input type=\"checkbox\" name=\"questions\" value=\"");
      out.print(q.getQuestionId());
      out.write("\"> \r\n");
      out.write("									<label>");
      out.print(q.getQuestionText());
      out.write("</label>\r\n");
      out.write("								<small>(Category: ");
      out.print(q.getCategory());
      out.write(")\r\n");
      out.write("								</small>\r\n");
      out.write("							</div>\r\n");
      out.write("							");

							}
							} else {
							
      out.write("\r\n");
      out.write("							<div class=\"no-questions\">No questions available</div>\r\n");
      out.write("							");

							}
							
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<button type=\"submit\" class=\"btn\">Create Quiz</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("		</main>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- close .layout -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
