/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-20 12:21:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.Admin;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.model.Admin");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Admin admin = (Admin) session.getAttribute("admin");
    if (admin == null) {
        response.sendRedirect(request.getContextPath() + "/admin/login");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Dashboard - Quiz App</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Reset */\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0; padding: 0; box-sizing: border-box;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            background: #f5f7fa;\r\n");
      out.write("            color: #34495a;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .layout {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 260px;\r\n");
      out.write("            background: linear-gradient(180deg, #4e73df 0%, #224abe 100%);\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 24px 20px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: space-between; /* space between top menu and logout */\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-top {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("        }\r\n");
      out.write("        .logo {\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 36px;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-item {\r\n");
      out.write("            padding: 14px 18px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            transition: background 0.25s ease;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-item:hover {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .menu-item.active {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.3);\r\n");
      out.write("            box-shadow: inset 3px 0 0 #f1f1f1;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn {\r\n");
      out.write("            padding: 14px 18px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background: #e74c3c; /* nice red color for logout */\r\n");
      out.write("            transition: background 0.3s ease;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .logout-btn:hover {\r\n");
      out.write("            background: #c0392b;\r\n");
      out.write("        }\r\n");
      out.write("        .main-content {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 40px 50px;\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            box-shadow: inset 0 0 20px #f0f0f0;\r\n");
      out.write("            overflow-y: auto;\r\n");
      out.write("        }\r\n");
      out.write("        .header {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            margin-bottom: 36px;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #7f8c8d;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .stats-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));\r\n");
      out.write("            gap: 28px;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .stat-card {\r\n");
      out.write("            background: #f9fafc;\r\n");
      out.write("            padding: 28px 32px;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(46, 61, 73, 0.1);\r\n");
      out.write("            user-select: none;\r\n");
      out.write("            transition: box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .stat-card:hover {\r\n");
      out.write("            box-shadow: 0 6px 20px rgba(46, 61, 73, 0.15);\r\n");
      out.write("        }\r\n");
      out.write("        .stat-card h3 {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #95a5a6;\r\n");
      out.write("            margin-bottom: 14px;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("        .stat-card .number {\r\n");
      out.write("            font-size: 40px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #4e73df;\r\n");
      out.write("            line-height: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .table-container {\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            padding: 32px 36px;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(46, 61, 73, 0.1);\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        .table-header {\r\n");
      out.write("            margin-bottom: 28px;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        .table-header h2 {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #2c3e50;\r\n");
      out.write("        }\r\n");
      out.write("        p {\r\n");
      out.write("            color: #7f8c8d;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            line-height: 1.5;\r\n");
      out.write("            margin-top: 0;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"layout\">\r\n");
      out.write("        <aside class=\"sidebar\">\r\n");
      out.write("            <div class=\"sidebar-top\">\r\n");
      out.write("                <div class=\"logo\">\r\n");
      out.write("                    🎯 QUIZ APP\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\" class=\"menu-item active\">📊 Dashboard</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/quizManager\" class=\"menu-item\">📝 Quiz Manager</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/questionList\" class=\"menu-item\">❓ Question Manager</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/addQuestion\" class=\"menu-item\">➕ Add New Question</a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/createQuiz\" class=\"menu-item\">🆕 Create Quiz</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/home.jsp\" class=\"logout-btn\">Logout</a>\r\n");
      out.write("        </aside>\r\n");
      out.write("        <main class=\"main-content\">\r\n");
      out.write("            <div class=\"header\">\r\n");
      out.write("                <h1>Dashboard</h1>\r\n");
      out.write("                <div class=\"welcome\">Welcome, ");
      out.print( admin.getFullName() != null ? admin.getFullName() : admin.getUsername() );
      out.write("!</div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <section class=\"stats-grid\">\r\n");
      out.write("                <div class=\"stat-card\">\r\n");
      out.write("                    <h3>TOTAL QUIZ</h3>\r\n");
      out.write("                    <div class=\"number\">");
      out.print( request.getAttribute("totalQuiz") != null ? request.getAttribute("totalQuiz") : "0" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"stat-card\">\r\n");
      out.write("                    <h3>TOTAL QUESTIONS</h3>\r\n");
      out.write("                    <div class=\"number\">");
      out.print( request.getAttribute("totalQuestions") != null ? request.getAttribute("totalQuestions") : "0" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"stat-card\">\r\n");
      out.write("                    <h3>TOTAL USERS</h3>\r\n");
      out.write("                    <div class=\"number\">");
      out.print( request.getAttribute("totalUsers") != null ? request.getAttribute("totalUsers") : "0" );
      out.write("</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("            \r\n");
      out.write("            <section class=\"table-container\">\r\n");
      out.write("                <div class=\"table-header\">\r\n");
      out.write("                    <h2>Instructions</h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <p  style=\"margin-top: 2px; font-weight:700; color: #151b8d;\">Click \"Quiz Manager\" to manage Quiz.</p>\r\n");
      out.write("                <p  style=\"margin-top: 2px; font-weight:700; color: #571b7e;\">Click \"Question Manager\" to add or delete Questions</p>\r\n");
      out.write("                <p   style=\"margin-top: 2px; font-weight:700; color: #151b8d;\">Click \"Add new Questions\" to add new questions</p>\r\n");
      out.write("                <p style=\"margin-top: 2px; font-weight:700; color: #571b7e;\">Click \"Create Quiz\" to add quiz by adding questions</p>\r\n");
      out.write("            </section>\r\n");
      out.write("        </main>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
