/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-10 12:26:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Admin Login - Quiz Portal</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        /* Reset */\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0; padding: 0; box-sizing: border-box;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        body, html {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: linear-gradient(135deg, #dbeafe 0%, #bfdbfe 100%);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-container {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.85);\r\n");
      out.write("            backdrop-filter: blur(12px);\r\n");
      out.write("            color: #1e3a8a;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 12px 40px rgba(30, 58, 138, 0.2);\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("            width: 90%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            min-height: 400px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-image {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            background: linear-gradient(135deg, #93c5fd 0%, #60a5fa 100%);\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("            font-size: 120px; /* Emoji or icon size */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-form {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 60px 50px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #1e3a8a;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 28px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #3b82f6;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"text\"],\r\n");
      out.write("        input[type=\"password\"] {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 14px 18px;\r\n");
      out.write("            border: 2px solid #93c5fd;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            background: #f0f9ff;\r\n");
      out.write("            transition: border-color 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input:focus {\r\n");
      out.write("            border-color: #3b82f6;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            box-shadow: 0 0 8px rgba(59, 130, 246, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 16px;\r\n");
      out.write("            background: linear-gradient(135deg, #3b82f6 0%, #1e40af 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(30, 58, 138, 0.3);\r\n");
      out.write("            transition: background 0.3s ease, transform 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login:hover {\r\n");
      out.write("            background: linear-gradient(135deg, #1e40af 0%, #1e3a8a 100%);\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error {\r\n");
      out.write("            background: #fee2e2;\r\n");
      out.write("            color: #b91c1c;\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(185, 28, 28, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 720px) {\r\n");
      out.write("            .login-container {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                border-radius: 24px;\r\n");
      out.write("            }\r\n");
      out.write("            .login-image, .login-form {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                padding: 40px 30px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"login-container\">\r\n");
      out.write("        <div class=\"login-image\">\r\n");
      out.write("            👋\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"login-form\">\r\n");
      out.write("            <h2>Welcome Back!</h2>\r\n");
      out.write("            ");
 if (request.getAttribute("error") != null) { 
      out.write("\r\n");
      out.write("                <div class=\"error\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <form action=\"\" method=\"post\" autocomplete=\"off\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"username\">Enter Admin Name</label>\r\n");
      out.write("                    <input type=\"text\" id=\"username\" name=\"username\" required autofocus />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label for=\"password\">Password</label>\r\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" required />\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"btn-login\">Login</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
