/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-10 11:39:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.Admin;
import com.model.Quiz;
import java.util.List;

public final class quizManager_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.model.Quiz");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.Admin");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Admin admin = (Admin) session.getAttribute("admin");
    if (admin == null) {
        response.sendRedirect(request.getContextPath() + "/admin/login");
        return;
    }
    List<Quiz> quizzes = (List<Quiz>) request.getAttribute("quizzes");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Quiz Manager - Quiz App</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0; padding: 0; box-sizing: border-box;\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            background: #e9f1f7;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            width: 280px;\r\n");
      out.write("            background: #064635; /* Dark green */\r\n");
      out.write("            color: #d4f1e4;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            padding: 30px 25px;\r\n");
      out.write("            box-shadow: 3px 0 8px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .logo {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #a8d5ba;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-item {\r\n");
      out.write("            padding: 14px 20px;\r\n");
      out.write("            margin-bottom: 12px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            color: #d4f1e4;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            transition: background 0.3s, color 0.3s;\r\n");
      out.write("            display: block;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-item:hover {\r\n");
      out.write("            background: #a8d5ba;\r\n");
      out.write("            color: #064635;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .menu-item.active {\r\n");
      out.write("            background: #1f7a5a;\r\n");
      out.write("            color: #e9f1f7;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("        .main-content {\r\n");
      out.write("            flex: 1;\r\n");
      out.write("            padding: 40px 50px;\r\n");
      out.write("            background: #ffffff;\r\n");
      out.write("            box-shadow: 0 0 20px rgba(0,0,0,0.08);\r\n");
      out.write("            border-radius: 20px 0 0 20px;\r\n");
      out.write("            overflow-x: auto;\r\n");
      out.write("        }\r\n");
      out.write("        h2 {\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #064635;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            font-size: 32px;\r\n");
      out.write("        }\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: separate;\r\n");
      out.write("            border-spacing: 0 15px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        thead th {\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            padding: 12px 20px;\r\n");
      out.write("            background: #e0f2f1;\r\n");
      out.write("            color: #004d40;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            border-radius: 10px 10px 0 0;\r\n");
      out.write("        }\r\n");
      out.write("        tbody tr {\r\n");
      out.write("            background: #f8fdfa;\r\n");
      out.write("            box-shadow: 0 3px 8px rgba(0,0,0,0.05);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            transition: transform 0.2s ease;\r\n");
      out.write("        }\r\n");
      out.write("        tbody tr:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 6px 15px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("        tbody td {\r\n");
      out.write("            padding: 18px 20px;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("            color: #054a3d;\r\n");
      out.write("        }\r\n");
      out.write("        tbody td:first-child {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #037a50;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-view {\r\n");
      out.write("            background-color: #1de9b6; /* teal */\r\n");
      out.write("            color: #004d40;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-view:hover {\r\n");
      out.write("            background-color: #00bfa5;\r\n");
      out.write("            color: white;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-edit {\r\n");
      out.write("            background-color: #64b5f6; /* light blue */\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            padding: 8px 16px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin: 0 8px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            transition: background 0.3s;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-edit:hover {\r\n");
      out.write("            background-color: #42a5f5;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-delete {\r\n");
      out.write("            background-color: #ef5350; /* red */\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-delete:hover {\r\n");
      out.write("            background-color: #d32f2f;\r\n");
      out.write("        }\r\n");
      out.write("        form {\r\n");
      out.write("            display: inline;\r\n");
      out.write("        }\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            body {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("            .sidebar {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                border-radius: 0 0 20px 20px;\r\n");
      out.write("                padding: 15px 10px;\r\n");
      out.write("                display: flex;\r\n");
      out.write("                flex-direction: row;\r\n");
      out.write("                overflow-x: auto;\r\n");
      out.write("            }\r\n");
      out.write("            .logo {\r\n");
      out.write("                flex: 0 0 auto;\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("                margin-bottom: 0;\r\n");
      out.write("                margin-right: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .menu-item {\r\n");
      out.write("                flex: 0 0 auto;\r\n");
      out.write("                margin-right: 10px;\r\n");
      out.write("                margin-bottom: 0;\r\n");
      out.write("                padding: 10px 14px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("            .main-content {\r\n");
      out.write("                padding: 20px 15px;\r\n");
      out.write("                border-radius: 0;\r\n");
      out.write("                box-shadow: none;\r\n");
      out.write("                overflow-x: scroll;\r\n");
      out.write("            }\r\n");
      out.write("            table {\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("            thead th, tbody td {\r\n");
      out.write("                padding: 12px 10px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"logo\">🎯 QUIZ APP</div>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\" class=\"menu-item\">📊 Dashboard</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/quizManager\" class=\"menu-item active\">📝 Quiz Manager</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/questionList\" class=\"menu-item\">❓ Question Manager</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/addQuestion\" class=\"menu-item\">➕ Add New Question</a>\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/createQuiz\" class=\"menu-item\">🆕 Create Quiz</a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <h2>Quiz Manager</h2>\r\n");
      out.write("        <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th>Sr No.</th>\r\n");
      out.write("                    <th>Quiz Title</th>\r\n");
      out.write("                    <th>Category</th>\r\n");
      out.write("                    <th>Created At</th>\r\n");
      out.write("                    <th>Action</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
 if (quizzes != null && !quizzes.isEmpty()) {
                    int srNo = 1;
                    for (Quiz quiz : quizzes) { 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>");
      out.print( srNo++ );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( quiz.getQuizTitle() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( quiz.getCategory() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( quiz.getCreatedAt() );
      out.write("</td>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/quizManager?action=view&quizId=");
      out.print( quiz.getQuizId() );
      out.write("\" class=\"btn btn-view\">View</a>\r\n");
      out.write("                                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/quizManager?action=edit&quizId=");
      out.print( quiz.getQuizId() );
      out.write("\" class=\"btn btn-edit\">Edit</a>\r\n");
      out.write("                                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/quizManager\" method=\"post\" onsubmit=\"return confirm('Are you sure you want to delete this quiz?');\" style=\"display:inline;\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"quizId\" value=\"");
      out.print( quiz.getQuizId() );
      out.write("\">\r\n");
      out.write("                                    <input type=\"hidden\" name=\"action\" value=\"delete\">\r\n");
      out.write("                                    <button type=\"submit\" class=\"btn btn-delete\">Delete</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                ");
 }
                } else { 
      out.write("\r\n");
      out.write("                    <tr><td colspan=\"5\" style=\"text-align: center; padding: 30px 0; color: #555;\">No quizzes found</td></tr>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
