/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-23 12:32:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.User;
import com.model.Quiz;
import com.model.Question;

public final class attemptQuiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.model.Quiz");
    _jspx_imports_classes.add("com.model.Question");
    _jspx_imports_classes.add("com.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect(request.getContextPath() + "/user/login");
        return;
    }
    Quiz quiz = (Quiz) request.getAttribute("quiz");
    Question question = (Question) request.getAttribute("question");
    int questionNumber = (Integer) request.getAttribute("questionNumber");
    int totalQuestions = (Integer) request.getAttribute("totalQuestions");
    Integer savedAnswer = (Integer) request.getAttribute("savedAnswer");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Attempt Quiz - ");
      out.print( quiz.getQuizTitle() );
      out.write("</title>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0; padding: 0; box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: #f0f4ff;\r\n");
      out.write("            color: #1a1a1a;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            padding: 40px 15px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(102, 126, 234, 0.3);\r\n");
      out.write("            padding: 35px 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .quiz-header {\r\n");
      out.write("            border-bottom: 2px solid #667eea;\r\n");
      out.write("            padding-bottom: 15px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .quiz-title {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        .question-progress {\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("        }\r\n");
      out.write("        .question-text {\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #222;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            line-height: 1.3;\r\n");
      out.write("        }\r\n");
      out.write("        form {\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        .option {\r\n");
      out.write("            background: #e9efff;\r\n");
      out.write("            border: 2px solid transparent;\r\n");
      out.write("            padding: 16px 22px;\r\n");
      out.write("            margin-bottom: 18px;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            color: #334680;\r\n");
      out.write("        }\r\n");
      out.write("        .option:hover {\r\n");
      out.write("            background: #d0dbff;\r\n");
      out.write("            border-color: #667eea;\r\n");
      out.write("        }\r\n");
      out.write("        .option.selected {\r\n");
      out.write("            background: #667eea;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-color: #4455cc;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(102, 126, 234, 0.7);\r\n");
      out.write("        }\r\n");
      out.write("        .option input[type=\"radio\"] {\r\n");
      out.write("            margin-right: 18px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            width: 20px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .navigation {\r\n");
      out.write("            margin-top: 40px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("        }\r\n");
      out.write("        .btn {\r\n");
      out.write("            background: #667eea;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 14px 36px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            box-shadow: 0 6px 16px rgba(102, 126, 234, 0.35);\r\n");
      out.write("            transition: background-color 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .btn:hover {\r\n");
      out.write("            background: #4455cc;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(68, 85, 204, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-previous {\r\n");
      out.write("            background: #9aa5c1;\r\n");
      out.write("            box-shadow: 0 6px 16px rgba(154, 165, 193, 0.35);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-previous:hover {\r\n");
      out.write("            background: #7c85a5;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(124, 133, 165, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-submit {\r\n");
      out.write("            background: #28a745;\r\n");
      out.write("            box-shadow: 0 6px 16px rgba(40, 167, 69, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-submit:hover {\r\n");
      out.write("            background: #1e7e34;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(30, 126, 52, 0.6);\r\n");
      out.write("        }\r\n");
      out.write("        @media (max-width: 600px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 25px 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .quiz-title {\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("            }\r\n");
      out.write("            .question-text {\r\n");
      out.write("                font-size: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .btn {\r\n");
      out.write("                padding: 12px 28px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("            .option {\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("                padding: 14px 18px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("        function selectOption(optionNum) {\r\n");
      out.write("            document.querySelectorAll('.option').forEach(opt => opt.classList.remove('selected'));\r\n");
      out.write("            const selectedOpt = document.getElementById('opt' + optionNum);\r\n");
      out.write("            if(selectedOpt) {\r\n");
      out.write("                selectedOpt.classList.add('selected');\r\n");
      out.write("            }\r\n");
      out.write("            const radioInput = document.getElementById('radio' + optionNum);\r\n");
      out.write("            if(radioInput) {\r\n");
      out.write("                radioInput.checked = true;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        window.addEventListener('DOMContentLoaded', () => {\r\n");
      out.write("            // Highlight saved answer on page load\r\n");
      out.write("            ");
 if (savedAnswer != null) { 
      out.write("\r\n");
      out.write("                selectOption(");
      out.print( savedAnswer );
      out.write(");\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("     <div style=\"width:100%; text-align:center;\">\r\n");
      out.write("    <h1>Welcome to quiz Portal</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"quiz-header\">\r\n");
      out.write("            <div class=\"quiz-title\">");
      out.print( quiz.getQuizTitle() );
      out.write("</div>\r\n");
      out.write("            <div class=\"question-progress\">Question ");
      out.print( questionNumber );
      out.write(" of ");
      out.print( totalQuestions );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"question-text\">");
      out.print( question.getQuestionText() );
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/attemptQuiz\" method=\"post\">\r\n");
      out.write("            <div class=\"option ");
      out.print( (savedAnswer != null && savedAnswer == 1) ? "selected" : "" );
      out.write("\" id=\"opt1\" onclick=\"selectOption(1)\">\r\n");
      out.write("                <input type=\"radio\" name=\"selectedOption\" value=\"1\" id=\"radio1\" ");
      out.print( (savedAnswer != null && savedAnswer == 1) ? "checked" : "" );
      out.write(" />\r\n");
      out.write("                <label for=\"radio1\">");
      out.print( question.getOption1() );
      out.write("</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"option ");
      out.print( (savedAnswer != null && savedAnswer == 2) ? "selected" : "" );
      out.write("\" id=\"opt2\" onclick=\"selectOption(2)\">\r\n");
      out.write("                <input type=\"radio\" name=\"selectedOption\" value=\"2\" id=\"radio2\" ");
      out.print( (savedAnswer != null && savedAnswer == 2) ? "checked" : "" );
      out.write(" />\r\n");
      out.write("                <label for=\"radio2\">");
      out.print( question.getOption2() );
      out.write("</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"option ");
      out.print( (savedAnswer != null && savedAnswer == 3) ? "selected" : "" );
      out.write("\" id=\"opt3\" onclick=\"selectOption(3)\">\r\n");
      out.write("                <input type=\"radio\" name=\"selectedOption\" value=\"3\" id=\"radio3\" ");
      out.print( (savedAnswer != null && savedAnswer == 3) ? "checked" : "" );
      out.write(" />\r\n");
      out.write("                <label for=\"radio3\">");
      out.print( question.getOption3() );
      out.write("</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"option ");
      out.print( (savedAnswer != null && savedAnswer == 4) ? "selected" : "" );
      out.write("\" id=\"opt4\" onclick=\"selectOption(4)\">\r\n");
      out.write("                <input type=\"radio\" name=\"selectedOption\" value=\"4\" id=\"radio4\" ");
      out.print( (savedAnswer != null && savedAnswer == 4) ? "checked" : "" );
      out.write(" />\r\n");
      out.write("                <label for=\"radio4\">");
      out.print( question.getOption4() );
      out.write("</label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"navigation\">\r\n");
      out.write("                ");
 if (questionNumber > 1) { 
      out.write("\r\n");
      out.write("                    <button type=\"submit\" name=\"action\" value=\"previous\" class=\"btn btn-previous\">Previous</button>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <div></div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
 if (questionNumber < totalQuestions) { 
      out.write("\r\n");
      out.write("                    <button type=\"submit\" name=\"action\" value=\"next\" class=\"btn btn-next\">Next</button>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <button type=\"submit\" name=\"action\" value=\"submit\" class=\"btn btn-submit\">Submit Quiz</button>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
