/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-20 11:44:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Online Quiz Portal</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Poppins', Arial, sans-serif;\r\n");
      out.write("	background: #f4f6f9; /* light neutral background */\r\n");
      out.write("	color: #222;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navbar */\r\n");
      out.write(".navbar {\r\n");
      out.write("	background: #1e3c72; /* deep blue */\r\n");
      out.write("	background: linear-gradient(90deg, #2a5298, #1e3c72);\r\n");
      out.write("	padding: 16px 50px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: space-between;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	box-shadow: 0 3px 8px rgba(0, 0, 0, 0.15);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-size: 28px;\r\n");
      out.write("	font-weight: 700;\r\n");
      out.write("	letter-spacing: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links a {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	margin-left: 25px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("	transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links a:hover {\r\n");
      out.write("	color: #ffd700; /* gold accent */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Hero Section */\r\n");
      out.write(".hero {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	background: linear-gradient(to right, #00c6ff, #0072ff);\r\n");
      out.write("	/* vibrant blue gradient */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 70px 20px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero h1 {\r\n");
      out.write("	font-size: 52px;\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	animation: fadeInDown 1s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero p {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	margin-bottom: 35px;\r\n");
      out.write("	max-width: 600px;\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes fadeInDown {from { opacity:0;\r\n");
      out.write("	transform: translateY(-25px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Call-to-action button */\r\n");
      out.write(".btn-login-hero {\r\n");
      out.write("	background: #ffd700; /* gold */\r\n");
      out.write("	color: #1e3c72;\r\n");
      out.write("	padding: 14px 40px;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.25);\r\n");
      out.write("	transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-login-hero:hover {\r\n");
      out.write("	transform: translateY(-2px);\r\n");
      out.write("	box-shadow: 0 6px 18px rgba(0, 0, 0, 0.35);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media ( max-width : 700px) {\r\n");
      out.write("	.navbar {\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		align-items: flex-start;\r\n");
      out.write("		padding: 12px 25px;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-links {\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-links a {\r\n");
      out.write("		margin: 8px 0;\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	.hero h1 {\r\n");
      out.write("		font-size: 36px;\r\n");
      out.write("	}\r\n");
      out.write("	.hero p {\r\n");
      out.write("		font-size: 16px;\r\n");
      out.write("		max-width: 90%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	font-family: 'Poppins', Arial, sans-serif;\r\n");
      out.write("	background: #f4f6f9; /* light neutral background */\r\n");
      out.write("	color: #222;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navbar */\r\n");
      out.write("\r\n");
      out.write("/* Navbar Container */\r\n");
      out.write(".navbar {\r\n");
      out.write("    background: linear-gradient(90deg, #1e3c72, #2a5298); /* Smooth gradient */\r\n");
      out.write("    padding: 14px 40px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);\r\n");
      out.write("    position: sticky;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Logo */\r\n");
      out.write(".logo {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    font-size: 26px;\r\n");
      out.write("    font-weight: 700;\r\n");
      out.write("    letter-spacing: 1.5px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    transition: transform 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logo:hover {\r\n");
      out.write("    transform: scale(1.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Navigation Links */\r\n");
      out.write(".nav-links a {\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    margin-left: 25px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    font-weight: 500;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    transition: color 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links a::after {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    width: 0%;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    bottom: -4px;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background-color: #ffd700; /* gold accent */\r\n");
      out.write("    transition: width 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links a:hover {\r\n");
      out.write("    color: #ffd700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-links a:hover::after {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive Design */\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("    .navbar {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        padding: 12px 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links {\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-links a {\r\n");
      out.write("        margin: 10px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Hero Section */\r\n");
      out.write(".hero {\r\n");
      out.write("	flex: 1;\r\n");
      out.write("	background: linear-gradient(to right, #00c6ff, #0072ff);\r\n");
      out.write("	/* vibrant blue gradient */\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 70px 20px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero h1 {\r\n");
      out.write("	font-size: 52px;\r\n");
      out.write("	font-weight: 800;\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("	animation: fadeInDown 1s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hero p {\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	margin-bottom: 35px;\r\n");
      out.write("	max-width: 600px;\r\n");
      out.write("	line-height: 1.6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes fadeInDown {from { opacity:0;\r\n");
      out.write("	transform: translateY(-25px);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("to {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Call-to-action button */\r\n");
      out.write(".btn-login-hero {\r\n");
      out.write("	background: rgb(175,214,255); /* green */\r\n");
      out.write("	color: #1e3c72;\r\n");
      out.write("	padding: 14px 40px;\r\n");
      out.write("	border-radius: 6px;\r\n");
      out.write("	font-size: 18px;\r\n");
      out.write("	font-weight: 600;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	box-shadow: 0 4px 12px rgba(0, 0, 0, 0.25);\r\n");
      out.write("	transition: transform 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-login-hero:hover {\r\n");
      out.write("	transform: translateY(-2px);\r\n");
      out.write("	box-shadow: 0 6px 18px rgba(0, 0, 0, 0.35);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Responsive */\r\n");
      out.write("@media ( max-width : 700px) {\r\n");
      out.write("	.navbar {\r\n");
      out.write("		flex-direction: column;\r\n");
      out.write("		align-items: flex-start;\r\n");
      out.write("		padding: 12px 25px;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-links {\r\n");
      out.write("		margin-top: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	.nav-links a {\r\n");
      out.write("		margin: 8px 0;\r\n");
      out.write("		font-size: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	.hero h1 {\r\n");
      out.write("		font-size: 36px;\r\n");
      out.write("	}\r\n");
      out.write("	.hero p {\r\n");
      out.write("		font-size: 16px;\r\n");
      out.write("		max-width: 90%;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav class=\"navbar\">\r\n");
      out.write("		<div class=\"logo\">ONLINE QUIZ</div>\r\n");
      out.write("		<div class=\"nav-links\">\r\n");
      out.write("			<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/login\">Admin\r\n");
      out.write("				Login</a> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/login\">Login/Signup</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"hero\">\r\n");
      out.write("		<h1>Welcome to Online Quiz Portal</h1>\r\n");
      out.write("		<p>Interactive quizzes that inspire you to learn and conquer challenges every day!</p>\r\n");
      out.write("		<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/login\"\r\n");
      out.write("			class=\"btn-login-hero\">Start</a>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
