/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-23 12:29:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.User;
import com.model.Quiz;
import java.util.List;

public final class quizList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.model.Quiz");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.model.User");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    User user = (User) session.getAttribute("user");
    if (user == null) {
        response.sendRedirect(request.getContextPath() + "/user/login");
        return;
    }
    List<Quiz> quizzes = (List<Quiz>) request.getAttribute("quizzes");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Welcome to Login Page</title>\r\n");
      out.write("    <div style=\"width:100%; text-align:center;\">\r\n");
      out.write("    <h1>Welcome to quiz Portal</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        * { margin: 0; padding: 0; box-sizing: border-box; }\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background: linear-gradient(135deg, #c0c0c0 0%, #a0a0a0 50%, #808080 100%);\r\n");
      out.write("            color: #222; /* Dark text for contrast */\r\n");
      out.write("        }\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background: #3a3a3a;\r\n");
      out.write("            padding: 18px 60px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: flex-end; /* Align items to right */\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0,0,0,0.25);\r\n");
      out.write("            gap: 30px; /* spacing between links */\r\n");
      out.write("        }\r\n");
      out.write("        .logo {\r\n");
      out.write("            color: #d75a4a; /* muted red */\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: 800;\r\n");
      out.write("            letter-spacing: 2px;\r\n");
      out.write("            cursor: default;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links a {\r\n");
      out.write("            color: #bbb;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links a:hover {\r\n");
      out.write("            color: #d75a4a;\r\n");
      out.write("        }\r\n");
      out.write("        .nav-links span.welcome-text {\r\n");
      out.write("            color: #bbb;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            max-width: 1200px;\r\n");
      out.write("            margin: 50px auto;\r\n");
      out.write("            padding: 0 30px;\r\n");
      out.write("        }\r\n");
      out.write("        h1 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            letter-spacing: 1.2px;\r\n");
      out.write("        }\r\n");
      out.write("        .quiz-grid {\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));\r\n");
      out.write("            gap: 28px;\r\n");
      out.write("        }\r\n");
      out.write("        .quiz-card {\r\n");
      out.write("            background: #f5f5f5;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            padding: 30px 25px 35px;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(0, 0, 0, 0.08);\r\n");
      out.write("            border-left: 6px solid #6fc1d9;\r\n");
      out.write("            transition: transform 0.35s ease, box-shadow 0.35s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            color: #222;\r\n");
      out.write("        }\r\n");
      out.write("        .quiz-card:hover {\r\n");
      out.write("            transform: translateY(-7px);\r\n");
      out.write("            box-shadow: 0 12px 30px rgba(111, 193, 217, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("        .quiz-category {\r\n");
      out.write("            align-self: flex-start;\r\n");
      out.write("            background: #6fc1d9;\r\n");
      out.write("            color: #1b2c3d;\r\n");
      out.write("            padding: 6px 18px;\r\n");
      out.write("            border-radius: 25px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            letter-spacing: 0.8px;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("        .quiz-card h3 {\r\n");
      out.write("            color: #222;\r\n");
      out.write("            font-size: 22px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            line-height: 1.2;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-start {\r\n");
      out.write("            align-self: flex-start;\r\n");
      out.write("            background: #d75a4a;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 12px 32px;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            box-shadow: 0 6px 14px rgba(215, 90, 74, 0.55);\r\n");
      out.write("            transition: background-color 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-start:hover {\r\n");
      out.write("            background: #bf4a3f;\r\n");
      out.write("            box-shadow: 0 8px 22px rgba(191, 74, 63, 0.75);\r\n");
      out.write("        }\r\n");
      out.write("        p.no-quizzes {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 80px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"navbar\">\r\n");
      out.write("        <div class=\"nav-links\">\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/home.jsp\">Logout</a>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\" style=\"text-align:center;\">\r\n");
      out.write("        <h1 style=\"color: #000080\">Start Attempting Questions</h1>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        ");
 if (quizzes != null && !quizzes.isEmpty()) { 
      out.write("\r\n");
      out.write("            <div class=\"quiz-grid\">\r\n");
      out.write("                ");
 for (Quiz quiz : quizzes) { 
      out.write("\r\n");
      out.write("                    <div class=\"quiz-card\">\r\n");
      out.write("                        <span class=\"quiz-category\">");
      out.print( quiz.getCategory() );
      out.write("</span>\r\n");
      out.write("                        <h3>");
      out.print( quiz.getQuizTitle() );
      out.write("</h3>\r\n");
      out.write("                        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/attemptQuiz?quizId=");
      out.print( quiz.getQuizId() );
      out.write("\" class=\"btn-start\">Start Quiz</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <p class=\"no-quizzes\">No quizzes available at the moment.</p>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
