/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-12-09 12:55:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.user;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.model.Quiz;
import com.model.Leaderboard;
import java.util.List;

public final class leaderboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("com.model.Quiz");
    _jspx_imports_classes.add("com.model.Leaderboard");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

    Quiz quiz = (Quiz) request.getAttribute("quiz");
    List<Leaderboard> leaderboard = (List<Leaderboard>) request.getAttribute("leaderboard");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Leaderboard</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0; padding: 0; box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;\r\n");
      out.write("            background: #022c43;\r\n");
      out.write("            color: #e0f7fa;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: flex-start;\r\n");
      out.write("            padding: 40px 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .container {\r\n");
      out.write("            background: #014d6d;\r\n");
      out.write("            max-width: 900px;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            box-shadow: 0 12px 30px rgba(0, 188, 212, 0.3);\r\n");
      out.write("            padding: 40px 35px;\r\n");
      out.write("        }\r\n");
      out.write("        .header {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-bottom: 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .quiz-name {\r\n");
      out.write("            color: #ff6f61;\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 6px;\r\n");
      out.write("            letter-spacing: 1.2px;\r\n");
      out.write("        }\r\n");
      out.write("        .category {\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #80deea;\r\n");
      out.write("            letter-spacing: 1.5px;\r\n");
      out.write("        }\r\n");
      out.write("        .leaderboard-table {\r\n");
      out.write("            background: #023e58;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            box-shadow: 0 6px 20px rgba(0, 0, 0, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("        table {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-collapse: separate;\r\n");
      out.write("            border-spacing: 0;\r\n");
      out.write("        }\r\n");
      out.write("        thead {\r\n");
      out.write("            background: #00bcd4;\r\n");
      out.write("        }\r\n");
      out.write("        th, td {\r\n");
      out.write("            padding: 16px 18px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #e0f7fa;\r\n");
      out.write("            letter-spacing: 0.05em;\r\n");
      out.write("        }\r\n");
      out.write("        th {\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            border-bottom: 2px solid #0288d1;\r\n");
      out.write("        }\r\n");
      out.write("        tbody tr {\r\n");
      out.write("            background: #014d6d;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("            cursor: default;\r\n");
      out.write("        }\r\n");
      out.write("        tbody tr:nth-child(odd) {\r\n");
      out.write("            background: #016987;\r\n");
      out.write("        }\r\n");
      out.write("        tbody tr:hover {\r\n");
      out.write("            background: #0288d1;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        /* Highlight top 3 ranks */\r\n");
      out.write("        .rank-1 {\r\n");
      out.write("            background: linear-gradient(90deg, #ffd54f 0%, #ffb300 100%) !important;\r\n");
      out.write("            color: #3e2723 !important;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("        .rank-2 {\r\n");
      out.write("            background: linear-gradient(90deg, #aed581 0%, #689f38 100%) !important;\r\n");
      out.write("            color: #263238 !important;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("        .rank-3 {\r\n");
      out.write("            background: linear-gradient(90deg, #81d4fa 0%, #0288d1 100%) !important;\r\n");
      out.write("            color: #0d47a1 !important;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-back {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-top: 35px;\r\n");
      out.write("            padding: 14px 38px;\r\n");
      out.write("            background: #ff6f61;\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            box-shadow: 0 8px 20px rgba(255, 111, 97, 0.55);\r\n");
      out.write("            transition: background-color 0.3s ease, box-shadow 0.3s ease;\r\n");
      out.write("            user-select: none;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-back:hover {\r\n");
      out.write("            background: #ff826f;\r\n");
      out.write("            box-shadow: 0 10px 28px rgba(255, 130, 111, 0.75);\r\n");
      out.write("        }\r\n");
      out.write("        /* Responsive tweaks */\r\n");
      out.write("        @media (max-width: 600px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                padding: 30px 20px;\r\n");
      out.write("            }\r\n");
      out.write("            th, td {\r\n");
      out.write("                padding: 12px 10px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("            .quiz-name {\r\n");
      out.write("                font-size: 22px;\r\n");
      out.write("            }\r\n");
      out.write("            .category {\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            ");
 if (quiz != null) { 
      out.write("\r\n");
      out.write("                <div class=\"quiz-name\">QUIZ NAME: ");
      out.print( quiz.getQuizTitle().toUpperCase() );
      out.write("</div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            <div class=\"category\">CATEGORY: ");
      out.print( quiz != null ? quiz.getCategory() : "ALL QUIZZES" );
      out.write("</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"leaderboard-table\">\r\n");
      out.write("            <table>\r\n");
      out.write("                <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th>SR NO</th>\r\n");
      out.write("                        <th>NAME</th>\r\n");
      out.write("                        <th>EMAIL</th>\r\n");
      out.write("                        <th>SCORE</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("                <tbody>\r\n");
      out.write("                    ");
 if (leaderboard != null && !leaderboard.isEmpty()) {
                        for (Leaderboard entry : leaderboard) {
                            String rankClass = "";
                            if (entry.getSrNo() == 1) rankClass = "rank-1";
                            else if (entry.getSrNo() == 2) rankClass = "rank-2";
                            else if (entry.getSrNo() == 3) rankClass = "rank-3";
                    
      out.write("\r\n");
      out.write("                        <tr class=\"");
      out.print( rankClass );
      out.write("\">\r\n");
      out.write("                            <td>");
      out.print( entry.getSrNo() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( entry.getUsername() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( entry.getEmail() );
      out.write("</td>\r\n");
      out.write("                            <td>");
      out.print( entry.getScore() );
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    ");
 }
                    } else { 
      out.write("\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td colspan=\"4\" style=\"text-align: center; color: #ffdede; padding: 20px 0;\">\r\n");
      out.write("                                No attempts yet\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("                </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/user/quizList\" class=\"btn-back\">Back to Quiz List</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
